import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["DARKIE_CODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["DARKIE_CODER_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("DARKIE_CODER_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  DARKIE_CODER_AUTO_HEAP_SNAPSHOT: truthy("DARKIE_CODER_AUTO_HEAP_SNAPSHOT"),
  DARKIE_CODER_GIT_BASH_PATH: process.env["DARKIE_CODER_GIT_BASH_PATH"],
  DARKIE_CODER_CONFIG: process.env["DARKIE_CODER_CONFIG"],
  DARKIE_CODER_CONFIG_CONTENT: process.env["DARKIE_CODER_CONFIG_CONTENT"],
  DARKIE_CODER_DISABLE_AUTOUPDATE: truthy("DARKIE_CODER_DISABLE_AUTOUPDATE"),
  DARKIE_CODER_ALWAYS_NOTIFY_UPDATE: truthy("DARKIE_CODER_ALWAYS_NOTIFY_UPDATE"),
  DARKIE_CODER_DISABLE_PRUNE: truthy("DARKIE_CODER_DISABLE_PRUNE"),
  DARKIE_CODER_DISABLE_TERMINAL_TITLE: truthy("DARKIE_CODER_DISABLE_TERMINAL_TITLE"),
  DARKIE_CODER_SHOW_TTFD: truthy("DARKIE_CODER_SHOW_TTFD"),
  DARKIE_CODER_DISABLE_AUTOCOMPACT: truthy("DARKIE_CODER_DISABLE_AUTOCOMPACT"),
  DARKIE_CODER_DISABLE_MODELS_FETCH: truthy("DARKIE_CODER_DISABLE_MODELS_FETCH"),
  DARKIE_CODER_DISABLE_MOUSE: truthy("DARKIE_CODER_DISABLE_MOUSE"),
  DARKIE_CODER_FAKE_VCS: process.env["DARKIE_CODER_FAKE_VCS"],
  DARKIE_CODER_SERVER_PASSWORD: process.env["DARKIE_CODER_SERVER_PASSWORD"],
  DARKIE_CODER_SERVER_USERNAME: process.env["DARKIE_CODER_SERVER_USERNAME"],
  DARKIE_CODER_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("DARKIE_CODER_DISABLE_FFF"),

  // Experimental
  DARKIE_CODER_EXPERIMENTAL_FILEWATCHER: Config.boolean("DARKIE_CODER_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  DARKIE_CODER_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("DARKIE_CODER_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  DARKIE_CODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("DARKIE_CODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  DARKIE_CODER_MODELS_URL: process.env["DARKIE_CODER_MODELS_URL"],
  DARKIE_CODER_MODELS_PATH: process.env["DARKIE_CODER_MODELS_PATH"],
  DARKIE_CODER_DB: process.env["DARKIE_CODER_DB"],

  DARKIE_CODER_WORKSPACE_ID: process.env["DARKIE_CODER_WORKSPACE_ID"],
  DARKIE_CODER_EXPERIMENTAL_WORKSPACES: enabledByExperimental("DARKIE_CODER_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get DARKIE_CODER_DISABLE_PROJECT_CONFIG() {
    return truthy("DARKIE_CODER_DISABLE_PROJECT_CONFIG")
  },
  get DARKIE_CODER_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("DARKIE_CODER_EXPERIMENTAL_REFERENCES")
  },
  get DARKIE_CODER_TUI_CONFIG() {
    return process.env["DARKIE_CODER_TUI_CONFIG"]
  },
  get DARKIE_CODER_CONFIG_DIR() {
    return process.env["DARKIE_CODER_CONFIG_DIR"]
  },
  get DARKIE_CODER_PURE() {
    return truthy("DARKIE_CODER_PURE")
  },
  get DARKIE_CODER_PERMISSION() {
    return process.env["DARKIE_CODER_PERMISSION"]
  },
  get DARKIE_CODER_PLUGIN_META_FILE() {
    return process.env["DARKIE_CODER_PLUGIN_META_FILE"]
  },
  get DARKIE_CODER_CLIENT() {
    return process.env["DARKIE_CODER_CLIENT"] ?? "cli"
  },
}
